In [1967]:
def display_img(src, description=None, is_src_url=False):
    from IPython.display import Image
    from IPython.core.display import HTML 
    if description is not None: print(description)
    if is_src_url:
        display(Image(url=src))
    else:
        display(Image(filename=src))

# Objective:
## Clean the rest of the data (except data cleaned in the previous notebook)

In [1968]:
import pandas as pd
import numpy as np

In [1969]:
df = pd.read_csv('final data/data')

In [1970]:
df.head(3)

,weight,method,rounds,time,rounds_format,referee,Red_Name,Red_Record,Red_Height,Red_Weight,...,Blue_Body_Success,Blue_Body_Attempt,Blue_Leg_Success,Blue_Leg_Attempt,Blue_Distance_Success,Blue_Distance_Attempt,Blue_Clinch_Success,Blue_Clinch_Attempt,Blue_Ground_Success,Blue_Ground_Attempt
0,Women's Flyweight Bout,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Mark Smith,Alexa Grasso,15-3-0,"5' 5""",125 lbs.,...,17,22,6,7,124,261,0,1,2,2
1,Bantamweight Bout,KO/TKO,2,4:19,3 Rnd (5-5-5),Herb Dean,Cub Swanson,28-13-0,"5' 8""",135 lbs.,...,15,18,7,7,37,64,12,14,13,24
2,Middleweight Bout,KO/TKO,2,3:12,3 Rnd (5-5-5),Chris Tognoni,Jordan Wright,12-4-0 (1 NC),"6' 2""",185 lbs.,...,12,12,0,0,19,29,28,31,14,20

In [1971]:
df.columns

Index(['weight', 'method', 'rounds', 'time', 'rounds_format', 'referee',
       'Red_Name', 'Red_Record', 'Red_Height', 'Red_Weight', 'Red_Reach',
       'Red_STANCE', 'Red_DOB', 'Red_SLpM', 'Red_Str. Acc.', 'Red_SApM',
       'Red_Str. Def', 'Red_TD Avg.', 'Red_TD Acc.', 'Red_TD Def.',
       'Red_Sub. Avg.', 'Blue_Name', 'Blue_Record', 'Blue_Height',
       'Blue_Weight', 'Blue_Reach', 'Blue_STANCE', 'Blue_DOB', 'Blue_SLpM',
       'Blue_Str. Acc.', 'Blue_SApM', 'Blue_Str. Def', 'Blue_TD Avg.',
       'Blue_TD Acc.', 'Blue_TD Def.', 'Blue_Sub. Avg.', 'Winner', 'Red_KD',
       'Red_Sig. str. %', 'Red_Td %', 'Red_Sub. att', 'Red_Rev', 'Red_Ctrl',
       'Red_Sig. str_Success', 'Red_Sig. str_Attempt', 'Red_Total str_Success',
       'Red_Total str_Attempt', 'Red_Td_Success', 'Red_Td_Attempt',
       'Red_Head_Success', 'Red_Head_Attempt', 'Red_Body_Success',
       'Red_Body_Attempt', 'Red_Leg_Success', 'Red_Leg_Attempt',
       'Red_Distance_Success', 'Red_Distance_Attempt', 'Red_Clinch_Success',
       'Red_Clinch_Attempt', 'Red_Ground_Success', 'Red_Ground_Attempt',
       'Blue_KD', 'Blue_Sig. str. %', 'Blue_Td %', 'Blue_Sub. att', 'Blue_Rev',
       'Blue_Ctrl', 'Blue_Sig. str_Success', 'Blue_Sig. str_Attempt',
       'Blue_Total str_Success', 'Blue_Total str_Attempt', 'Blue_Td_Success',
       'Blue_Td_Attempt', 'Blue_Head_Success', 'Blue_Head_Attempt',
       'Blue_Body_Success', 'Blue_Body_Attempt', 'Blue_Leg_Success',
       'Blue_Leg_Attempt', 'Blue_Distance_Success', 'Blue_Distance_Attempt',
       'Blue_Clinch_Success', 'Blue_Clinch_Attempt', 'Blue_Ground_Success',
       'Blue_Ground_Attempt'],
      dtype='object')

# Making 'weight' feature name clearer:

In [1972]:
df = df.rename(columns={'weight' : 'weight_division'})

In [1973]:
df = df[[
    'weight_division', 'method', 'rounds', 'time', 'rounds_format', 'referee',
       'Red_Name', 'Red_Record', 'Red_Height', 'Red_Weight', 'Red_Reach',
       'Red_STANCE', 'Red_DOB', 'Red_SLpM', 'Red_Str. Acc.', 'Red_SApM',
       'Red_Str. Def', 'Red_TD Avg.', 'Red_TD Acc.', 'Red_TD Def.',
       'Red_Sub. Avg.', 'Blue_Name', 'Blue_Record', 'Blue_Height',
       'Blue_Weight', 'Blue_Reach', 'Blue_STANCE', 'Blue_DOB', 'Blue_SLpM',
       'Blue_Str. Acc.', 'Blue_SApM', 'Blue_Str. Def', 'Blue_TD Avg.',
       'Blue_TD Acc.', 'Blue_TD Def.', 'Blue_Sub. Avg.', 'Winner'
]]

df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,6500,6501,6502,6503,6504,6505,6506,6507,6508,6509
weight_division,Women's Flyweight Bout,Bantamweight Bout,Middleweight Bout,Bantamweight Bout,Light Heavyweight Bout,Bantamweight Bout,Middleweight Bout,Featherweight Bout,Women's Strawweight Bout,Flyweight Bout,...,Lightweight Bout,Lightweight Bout,Heavyweight Bout,Middleweight Bout,Heavyweight Bout,Middleweight Bout,Heavyweight Bout,Middleweight Bout,Heavyweight Bout,Heavyweight Bout
method,Decision - Unanimous,KO/TKO,KO/TKO,Decision - Unanimous,KO/TKO,Decision - Split,Decision - Unanimous,Submission,Decision - Unanimous,Submission,...,KO/TKO,TKO - Doctor's Stoppage,KO/TKO,KO/TKO,KO/TKO,Submission,Decision - Unanimous,KO/TKO,Submission,TKO - Doctor's Stoppage
rounds,5,2,2,3,1,3,3,1,3,2,...,1,1,1,1,1,1,2,1,1,1
time,5:00,4:19,3:12,5:00,1:28,5:00,5:00,2:02,5:00,4:19,...,1:23,1:21,0:28,9:56,0:43,12:00,3:00,2:58,1:56,10:01
rounds_format,5 Rnd (5-5-5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),...,1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3),1 Rnd + OT (12-3)
referee,Mark Smith,Herb Dean,Chris Tognoni,Kerry Hatley,Mark Smith,Herb Dean,Mark Smith,Chris Tognoni,Jerin Valel,Kerry Hatley,...,John McCarthy,Mario Yamasaki,John McCarthy,John McCarthy,John McCarthy,John McCarthy,John McCarthy,John McCarthy,Tony Mullinax,Tony Mullinax
Red_Name,Alexa Grasso,Cub Swanson,Jordan Wright,Raphael Assuncao,Misha Cirkunov,Mana Martinez,Nick Maximov,Joanderson Brito,Piera Rodriguez,Tatsuro Taira,...,Marcelo Mello,Laverne Clark,Ron Waterman,Tito Ortiz,Gary Goodridge,Jeremy Horn,Kevin Randleman,Evan Tanner,Pete Williams,Sione Latu
Red_Record,15-3-0,28-13-0,12-4-0 (1 NC),28-9-0,15-9-0,10-3-0,8-2-0,14-3-1,9-0-0,12-0-0,...,1-0-0,27-21-1,16-6-2,19-12-1,23-22-1,91-22-5 (1 NC),17-16-0,32-8-0,12-6-0,1-0-0
Red_Height,"5' 5""","5' 8""","6' 2""","5' 5""","6' 3""","5' 10""","6' 0""","5' 8""","5' 3""","5' 7""",...,"5' 7""","5' 11""","6' 2""","6' 3""","6' 3""","6' 1""","5' 10""","6' 0""","6' 3""","6' 0"""
Red_Weight,125 lbs.,135 lbs.,185 lbs.,135 lbs.,205 lbs.,135 lbs.,185 lbs.,145 lbs.,115 lbs.,125 lbs.,...,170 lbs.,170 lbs.,280 lbs.,205 lbs.,249 lbs.,185 lbs.,205 lbs.,185 lbs.,235 lbs.,215 lbs.
Red_Reach,"66""","70""","77""","66""","77""","70""","76""","72""","63""","70""",...,--,--,--,"74""",--,"74""",--,"74""",--,--
Red_STANCE,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Southpaw,Orthodox,Orthodox,Orthodox,...,Southpaw,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,NaN
Red_DOB,"Aug 09, 1993","Nov 02, 1983","Oct 07, 1991","Jul 19, 1982","Feb 27, 1987","Mar 25, 1996","Dec 23, 1997","Feb 11, 1995","Nov 11, 1992","Jan 27, 2000",...,--,"Dec 02, 1973","Nov 23, 1965","Jan 23, 1975","Jan 17, 1966","Aug 25, 1975","Aug 10, 1971","Feb 11, 1971","Jul 10, 1975",--
Red_SLpM,5.14,4.68,5.67,3.24,3.86,4.43,1.93,3.65,3.91,3.25,...,0.0,0.0,0.84,2.59,1.84,1.19,1.26,3.05,0.61,0.0
Red_Str. Acc.,44%,50%,65%,41%,51%,51%,45%,49%,47%,64%,...,0%,0%,50%,46%,56%,39%,54%,59%,62%,0%
Red_SApM,4.02,3.73,7.54,2.41,3.06,4.03,2.64,3.08,3.02,1.15,...,0.0,0.0,1.37,2.88,2.14,1.99,1.12,2.64,2.77,0.0
Red_Str. Def,61%,60%,32%,67%,57%,49%,46%,50%,60%,56%,...,0%,0%,42%,60%,48%,55%,57%,56%,40%,0%
Red_TD Avg.,0.44,1.09,3.6,1.47,4.15,0.95,4.16,3.76,3.67,2.47,...,0.0,0.0,4.19,2.47,0.4,1.83,2.0,2.55,1.84,0.0
Red_TD Acc.,57%,52%,50%,38%,39%,42%,45%,70%,39%,30%,...,0%,0%,69%,35%,100%,38%,56%,43%,40%,0%
Red_TD Def.,64%,61%,100%,78%,76%,27%,35%,0%,77%,60%,...,0%,0%,50%,54%,53%,29%,30%,25%,16%,0%
Red_Sub. Avg.,0.6,0.4,0.7,0.3,1.7,0.6,0.2,0.5,0.0,3.1,...,0.0,0.0,2.8,0.6,0.8,1.1,0.8,1.3,0.9,0.0
Blue_Name,Viviane Araujo,Jonathan Martinez,Dusko Todorovic,Victor Henry,Alonzo Menifield,Brandon Davis,Jacob Malkoun,Lucas Alexander,Sam Hughes,CJ Vergara,...,David Roberts,Fabiano Iha,Chris Condo,Guy Mezger,Andre Roberts,Chuck Liddell,Maurice Smith,Valeri Ignatov,Jason Godsey,Joey Roberts
Blue_Record,11-4-0,17-4-0,12-3-0,22-6-0,13-3-0,14-10-0,7-2-0,7-3-0,7-5-0,10-4-1,...,5-8-0,9-5-0,0-1-0,30-14-2,14-2-1,21-8-0,12-14-0,1-2-0,16-16-0,4-3-0
Blue_Height,"5' 4""","5' 8""","6' 1""","5' 7""","6' 0""","5' 10""","5' 9""","5' 11""","5' 5""","5' 6""",...,"6' 1""","5' 8""","6' 0""","6' 1""","6' 2""","6' 2""","6' 2""","5' 9""","6' 2""","6' 2"""
Blue_Weight,125 lbs.,135 lbs.,185 lbs.,135 lbs.,205 lbs.,135 lbs.,185 lbs.,145 lbs.,115 lbs.,125 lbs.,...,170 lbs.,155 lbs.,335 lbs.,200 lbs.,345 lbs.,205 lbs.,221 lbs.,170 lbs.,230 lbs.,200 lbs.
Blue_Reach,"68""","70""","74""","68""","76""","72""","73""","73""","64""","68""",...,--,--,--,--,--,"76""",--,--,--,--
Blue_STANCE,Orthodox,Southpaw,Orthodox,Switch,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,...,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox,NaN
Blue_DOB,"Nov 21, 1986","Apr 20, 1994","May 19, 1994","May 04, 1987","Oct 18, 1987","May 08, 1990","Aug 26, 1995","Jul 28, 1995","Jun 28, 1992","Jun 18, 1991",...,"Nov 15, 1975","Jul 28, 1970",--,"Jan 01, 1968","Feb 24, 1965","Dec 17, 1969","Dec 13, 1961",--,--,--
Blue_SLpM,4.82,4.84,5.64,7.87,3.91,4.68,3.7,0.49,3.93,4.83,...,0.0,1.73,0.0,2.3,0.0,2.97,0.41,0.0,0.0,0.0
Blue_Str. Acc.,48%,49%,57%,49%,56%,35%,55%,50%,47%,56%,...,0%,47%,0%,32%,0%,35%,46%,0%,0%,0%
Blue_SApM,5.33,3.88,4.54,6.47,3.24,4.62,2.64,1.97,4.88,4.63,...,0.0,2.49,0.0,1.36,0.0,2.71,0.47,0.0,0.0,0.0
Blue_Str. Def,56%,58%,47%,47%,52%,58%,50%,50%,52%,51%,...,0%,42%,0%,72%,0%,56%,60%,0%,0%,0%
Blue_TD Avg.,2.03,0.51,0.99,0.0,0.81,0.74,7.46,0.0,1.14,0.0,...,0.0,2.88,0.0,0.39,0.0,0.44,0.89,0.0,0.0,0.0
Blue_TD Acc.,48%,45%,12%,0%,30%,42%,44%,0%,37%,0%,...,0%,40%,0%,50%,0%,75%,50%,0%,0%,0%
Blue_TD Def.,90%,70%,45%,75%,85%,57%,0%,0%,47%,73%,...,0%,50%,0%,88%,0%,81%,20%,0%,0%,0%
Blue_Sub. Avg.,0.5,0.0,0.0,0.0,0.2,0.1,0.5,0.0,0.0,0.0,...,0.0,2.9,0.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0
Winner,Alexa Grasso,Jonathan Martinez,Dusko Todorovic,Raphael Assuncao,Alonzo Menifield,Mana Martinez,Jacob Malkoun,Joanderson Brito,Piera Rodriguez,Tatsuro Taira,...,Marcelo Mello,Laverne Clark,Ron Waterman,Tito Ortiz,Gary Goodridge,Jeremy Horn,Kevin Randleman,Evan Tanner,Pete Williams,Sione Latu

# Spotted NaN values in the last record, stance feature. Let's find all of them

In [1974]:
df = df.replace({ '--' : np.NaN, 
            '---' : np.NaN})

In [1975]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6510 entries, 0 to 6509
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   weight_division  6510 non-null   object
 1   method           6510 non-null   object
 2   rounds           6510 non-null   int64
 3   time             6510 non-null   object
 4   rounds_format    6510 non-null   object
 5   referee          6479 non-null   object
 6   Red_Name         6510 non-null   object
 7   Red_Record       6510 non-null   object
 8   Red_Height       6509 non-null   object
 9   Red_Weight       6510 non-null   object
 10  Red_Reach        6256 non-null   object
 11  Red_STANCE       6489 non-null   object
 12  Red_DOB          6497 non-null   object
 13  Red_SLpM         6510 non-null   float64
 14  Red_Str. Acc.    6510 non-null   object
 15  Red_SApM         6510 non-null   float64
 16  Red_Str. Def     6510 non-null   object
 17  Red_TD Avg.      6510 non-null   float64
 18  Red_TD Acc.      6510 non-null   object
 19  Red_TD Def.      6510 non-null   object
 20  Red_Sub. Avg.    6510 non-null   float64
 21  Blue_Name        6510 non-null   object
 22  Blue_Record      6510 non-null   object
 23  Blue_Height      6508 non-null   object
 24  Blue_Weight      6510 non-null   object
 25  Blue_Reach       5796 non-null   object
 26  Blue_STANCE      6462 non-null   object
 27  Blue_DOB         6447 non-null   object
 28  Blue_SLpM        6510 non-null   float64
 29  Blue_Str. Acc.   6510 non-null   object
 30  Blue_SApM        6510 non-null   float64
 31  Blue_Str. Def    6510 non-null   object
 32  Blue_TD Avg.     6510 non-null   float64
 33  Blue_TD Acc.     6510 non-null   object
 34  Blue_TD Def.     6510 non-null   object
 35  Blue_Sub. Avg.   6510 non-null   float64
 36  Winner           6510 non-null   object
dtypes: float64(8), int64(1), object(28)
memory usage: 1.8+ MB

In [1976]:
def get_nan_columns(df):
    nan_cols = []
    for col in df.columns:
        if len(df[df[col].isna()]) > 0:
            nan_cols.append(col)
    return nan_cols

In [1977]:
nan_cols = get_nan_columns(df)
nan_cols

['referee',
 'Red_Height',
 'Red_Reach',
 'Red_STANCE',
 'Red_DOB',
 'Blue_Height',
 'Blue_Reach',
 'Blue_STANCE',
 'Blue_DOB']

In [1978]:
df.groupby('Red_STANCE')['Red_STANCE'].count()

Red_STANCE
Open Stance      15
Orthodox       4903
Southpaw       1320
Switch          251
Name: Red_STANCE, dtype: int64

In [1979]:
df.groupby('Blue_STANCE')['Blue_STANCE'].count()

Blue_STANCE
Open Stance       8
Orthodox       4887
Sideways          1
Southpaw       1260
Switch          306
Name: Blue_STANCE, dtype: int64

# Imputing missing stance values with the most prevalent - Orthodox

In [1980]:
df.loc[df.Red_STANCE.isna(), 'Red_STANCE'] = 'Orthodox'
df.loc[df.Blue_STANCE.isna(), 'Blue_STANCE'] = 'Orthodox'

In [1981]:
nan_cols = get_nan_columns(df)
nan_cols

['referee',
 'Red_Height',
 'Red_Reach',
 'Red_DOB',
 'Blue_Height',
 'Blue_Reach',
 'Blue_DOB']

# Let's work on referees now

- Since fights are sorted in chronological order, it is unlikely for referee to be the same in X years, as he could get, for example, fired by that moment
- Thus, I'll try to find the most frequent referee -75 and +75 fights away from the fight with a missing referee and impute the missing value with his name

In [1982]:
df[df.referee.isna()].referee

784     NaN
907     NaN
1002    NaN
1065    NaN
1102    NaN
1160    NaN
1217    NaN
1286    NaN
1491    NaN
1633    NaN
1731    NaN
2033    NaN
2146    NaN
2151    NaN
2186    NaN
2670    NaN
3128    NaN
3162    NaN
3166    NaN
3208    NaN
3248    NaN
3527    NaN
3535    NaN
3851    NaN
4105    NaN
4106    NaN
4271    NaN
4348    NaN
4352    NaN
4493    NaN
4836    NaN
Name: referee, dtype: object

In [1983]:
from random import randint

def impute_referee(df, row):
    most_freq_referees = df.iloc[row-75:row+75, :].referee.mode()
    n = len(most_freq_referees)
    # if there are more referees with same frequency, let randomness choose for us
    if n > 1:
        return most_freq_referees[randint(1,10) % n]
    return most_freq_referees[0]

In [1984]:
missing_referees_rows = df.index[df.referee.isna()].tolist()

for row in missing_referees_rows:
    df.loc[row, 'referee'] = impute_referee(df, row)

In [1985]:
nan_cols = get_nan_columns(df)
nan_cols

['Red_Height', 'Red_Reach', 'Red_DOB', 'Blue_Height', 'Blue_Reach', 'Blue_DOB']

In [1986]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6510 entries, 0 to 6509
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   weight_division  6510 non-null   object
 1   method           6510 non-null   object
 2   rounds           6510 non-null   int64
 3   time             6510 non-null   object
 4   rounds_format    6510 non-null   object
 5   referee          6510 non-null   object
 6   Red_Name         6510 non-null   object
 7   Red_Record       6510 non-null   object
 8   Red_Height       6509 non-null   object
 9   Red_Weight       6510 non-null   object
 10  Red_Reach        6256 non-null   object
 11  Red_STANCE       6510 non-null   object
 12  Red_DOB          6497 non-null   object
 13  Red_SLpM         6510 non-null   float64
 14  Red_Str. Acc.    6510 non-null   object
 15  Red_SApM         6510 non-null   float64
 16  Red_Str. Def     6510 non-null   object
 17  Red_TD Avg.      6510 non-null   float64
 18  Red_TD Acc.      6510 non-null   object
 19  Red_TD Def.      6510 non-null   object
 20  Red_Sub. Avg.    6510 non-null   float64
 21  Blue_Name        6510 non-null   object
 22  Blue_Record      6510 non-null   object
 23  Blue_Height      6508 non-null   object
 24  Blue_Weight      6510 non-null   object
 25  Blue_Reach       5796 non-null   object
 26  Blue_STANCE      6510 non-null   object
 27  Blue_DOB         6447 non-null   object
 28  Blue_SLpM        6510 non-null   float64
 29  Blue_Str. Acc.   6510 non-null   object
 30  Blue_SApM        6510 non-null   float64
 31  Blue_Str. Def    6510 non-null   object
 32  Blue_TD Avg.     6510 non-null   float64
 33  Blue_TD Acc.     6510 non-null   object
 34  Blue_TD Def.     6510 non-null   object
 35  Blue_Sub. Avg.   6510 non-null   float64
 36  Winner           6510 non-null   object
dtypes: float64(8), int64(1), object(28)
memory usage: 1.8+ MB

# Let's work on heights now. Things to consider:
- Weight division matters - the heavier it is, the higher the fighter is
- Reach of the fighter

In [1987]:
df[df['Red_Height'].isna()][['weight_division', 'Red_Height', 'Red_Reach']]

             weight_division Red_Height Red_Reach
5159  Light Heavyweight Bout        NaN       NaN

## As seen above, the division of this fight is 'Light Heavyweight Bout'.  Reach is missing, so it's of no help

In [1988]:
df[df['weight_division'] == 'Light Heavyweight Bout'].Red_Height

4       6' 3"
39      6' 6"
64      6' 3"
74      6' 0"
83      6' 2"
        ...
6399    6' 0"
6404    6' 2"
6415    6' 0"
6420    6' 2"
6423    6' 0"
Name: Red_Height, Length: 560, dtype: object

## Let's convert height into centimeters

In [1989]:
def height_to_cm(x):
    x = x.split(' ')
    feet = int(x[0].split('\'')[0])
    inches = int(x[1].split('"')[0])
    inches += feet * 12
    return inches * 2.54

In [1990]:
mask = ~df['Red_Height'].isna()
df.loc[mask, 'Red_Height'] = df[mask].Red_Height.apply(lambda x: height_to_cm(x)).astype(float)

In [1991]:
mask = ~df['Blue_Height'].isna()
df.loc[mask, 'Blue_Height'] = df[mask].Blue_Height.apply(lambda x: height_to_cm(x)).astype(float)

In [1992]:
# Setting proper data type
df = df.astype({'Red_Height': 'float', 'Blue_Height': 'float'})
df[['Red_Height', 'Blue_Height']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6510 entries, 0 to 6509
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Red_Height   6509 non-null   float64
 1   Blue_Height  6508 non-null   float64
dtypes: float64(2)
memory usage: 101.8 KB

## Let's also convert reach into centimeters, while we are at it

In [1993]:
def reach_to_cm(x):
    inches = int(x.split('"')[0])
    return inches * 2.54

In [1994]:
mask = ~df['Red_Reach'].isna()
df.loc[mask, 'Red_Reach'] = df[mask].Red_Reach.apply(lambda x: reach_to_cm(x))

In [1995]:
mask = ~df['Blue_Reach'].isna()
df.loc[mask, 'Blue_Reach'] = df[mask].Blue_Reach.apply(lambda x: reach_to_cm(x))

In [1996]:
df = df.astype({'Red_Reach': 'float', 'Blue_Height': 'float'})

## Finally imputing Red_Height

In [1997]:
df[df.Red_Height.isna()]

,weight_division,method,rounds,time,rounds_format,referee,Red_Name,Red_Record,Red_Height,Red_Weight,...,Blue_DOB,Blue_SLpM,Blue_Str. Acc.,Blue_SApM,Blue_Str. Def,Blue_TD Avg.,Blue_TD Acc.,Blue_TD Def.,Blue_Sub. Avg.,Winner
5159,Light Heavyweight Bout,Submission,1,2:45,3 Rnd (5-5-5),John Sharp,Tom Blackledge,10-7-0,NaN,205 lbs.,...,"Oct 05, 1972",2.27,43%,3.77,53%,2.03,22%,33%,1.1,Anthony Perosh

* Imputing it with a mean height value of this weight division

In [1998]:
mask = df['weight_division'] == 'Light Heavyweight Bout'
mean_lhb_weight = pd.concat([df[mask].Red_Height, df[mask].Blue_Height]).mean()
mean_lhb_weight

187.31535299374443

In [1999]:
df.loc[df.Red_Height.isna(), 'Red_Height'] = mean_lhb_weight

In [2000]:
nan_cols = get_nan_columns(df)
nan_cols

['Red_Reach', 'Red_DOB', 'Blue_Height', 'Blue_Reach', 'Blue_DOB']

## Let's impute Blue_Height in the same manner

In [2001]:
df[df['Blue_Height'].isna()]

,weight_division,method,rounds,time,rounds_format,referee,Red_Name,Red_Record,Red_Height,Red_Weight,...,Blue_DOB,Blue_SLpM,Blue_Str. Acc.,Blue_SApM,Blue_Str. Def,Blue_TD Avg.,Blue_TD Acc.,Blue_TD Def.,Blue_Sub. Avg.,Winner
4956,Lightweight Bout,Submission,1,0:17,3 Rnd (5-5-5),Leon Roberts,Terry Etim,16-5-0,185.42,155 lbs.,...,"Jul 15, 1984",2.28,32%,6.25,44%,1.01,25%,33%,0.0,Terry Etim
5071,Lightweight Bout,KO/TKO,1,4:42,3 Rnd (5-5-5),Mark Matheny,Michael Johnson,21-18-0,177.80,155 lbs.,...,"Jul 15, 1984",2.28,32%,6.25,44%,1.01,25%,33%,0.0,Michael Johnson

In [2002]:
mask = df['weight_division'] == 'Lightweight Bout'

In [2003]:
mean_lb_weight = pd.concat([df[mask].Red_Height, df[mask].Blue_Height]).mean()
mean_lb_weight

176.8178057553957

In [2004]:
df.loc[df.Blue_Height.isna(), 'Blue_Height'] = mean_lb_weight

In [2005]:
nan_cols = get_nan_columns(df)
nan_cols

['Red_Reach', 'Red_DOB', 'Blue_Reach', 'Blue_DOB']

# Reach

In [2006]:
df[nan_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6510 entries, 0 to 6509
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Red_Reach   6256 non-null   float64
 1   Red_DOB     6497 non-null   object
 2   Blue_Reach  5796 non-null   object
 3   Blue_DOB    6447 non-null   object
dtypes: float64(1), object(3)
memory usage: 203.6+ KB

## It's a statistically known fact that height:reach ratio for an average human being is 1:1. Thus it can be said that reach adds no value to already existing columns indicating height

In [2007]:
df = df.drop(columns=['Red_Reach', 'Blue_Reach'])

In [2008]:
nan_cols = get_nan_columns(df)
nan_cols

['Red_DOB', 'Blue_DOB']

# Missing date of birth
- DOB might impact fight outcome seriously, as, say, 38+ yo fighter is likely to be out of shape, unless he is on steroids and is not tested by anti-doping agency, and thus is likely to lose against a 30 yo fighter

In [2009]:
df[nan_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6510 entries, 0 to 6509
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Red_DOB   6497 non-null   object
 1   Blue_DOB  6447 non-null   object
dtypes: object(2)
memory usage: 101.8+ KB

In [2010]:
df.shape[0] - df.dropna(axis=0).shape[0]

73

## Not many rows have missing date of birth
- imputing it does not sound like a good idea
- trying to google DOB of these fighters is time-inefficient
- thus, I'll just drop it

In [2011]:
df = df.dropna(axis=0)
df.shape

(6437, 35)

In [2012]:
nan_cols = get_nan_columns(df)
assert len(nan_cols) == 0

In [2013]:
df.head(1)['Red_DOB']

0    Aug 09, 1993
Name: Red_DOB, dtype: object

## We need to preserve year of birth only

In [2014]:
df.loc[:, 'Red_DOB']  = df['Red_DOB'].str[-4:]
df.loc[:, 'Blue_DOB'] = df['Blue_DOB'].str[-4:]

In [2015]:
df = df.astype({'Red_DOB':'int', 'Blue_DOB':'int'})

# Let's take a look at what remains to be done

In [2016]:
df.head(5).transpose()

,0,1,2,3,4
weight_division,Women's Flyweight Bout,Bantamweight Bout,Middleweight Bout,Bantamweight Bout,Light Heavyweight Bout
method,Decision - Unanimous,KO/TKO,KO/TKO,Decision - Unanimous,KO/TKO
rounds,5,2,2,3,1
time,5:00,4:19,3:12,5:00,1:28
rounds_format,5 Rnd (5-5-5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5)
referee,Mark Smith,Herb Dean,Chris Tognoni,Kerry Hatley,Mark Smith
Red_Name,Alexa Grasso,Cub Swanson,Jordan Wright,Raphael Assuncao,Misha Cirkunov
Red_Record,15-3-0,28-13-0,12-4-0 (1 NC),28-9-0,15-9-0
Red_Height,165.1,172.72,187.96,165.1,190.5
Red_Weight,125 lbs.,135 lbs.,185 lbs.,135 lbs.,205 lbs.
Red_STANCE,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox
Red_DOB,1993,1983,1991,1982,1987
Red_SLpM,5.14,4.68,5.67,3.24,3.86
Red_Str. Acc.,44%,50%,65%,41%,51%
Red_SApM,4.02,3.73,7.54,2.41,3.06
Red_Str. Def,61%,60%,32%,67%,57%
Red_TD Avg.,0.44,1.09,3.6,1.47,4.15
Red_TD Acc.,57%,52%,50%,38%,39%
Red_TD Def.,64%,61%,100%,78%,76%
Red_Sub. Avg.,0.6,0.4,0.7,0.3,1.7
Blue_Name,Viviane Araujo,Jonathan Martinez,Dusko Todorovic,Victor Henry,Alonzo Menifield
Blue_Record,11-4-0,17-4-0,12-3-0,22-6-0,13-3-0
Blue_Height,162.56,172.72,185.42,170.18,182.88
Blue_Weight,125 lbs.,135 lbs.,185 lbs.,135 lbs.,205 lbs.
Blue_STANCE,Orthodox,Southpaw,Orthodox,Switch,Orthodox
Blue_DOB,1986,1994,1994,1987,1987
Blue_SLpM,4.82,4.84,5.64,7.87,3.91
Blue_Str. Acc.,48%,49%,57%,49%,56%
Blue_SApM,5.33,3.88,4.54,6.47,3.24
Blue_Str. Def,56%,58%,47%,47%,52%
Blue_TD Avg.,2.03,0.51,0.99,0.0,0.81
Blue_TD Acc.,48%,45%,12%,0%,30%
Blue_TD Def.,90%,70%,45%,75%,85%
Blue_Sub. Avg.,0.5,0.0,0.0,0.0,0.2
Winner,Alexa Grasso,Jonathan Martinez,Dusko Todorovic,Raphael Assuncao,Alonzo Menifield

# TODO:
- **[X]** remove '%' sign from all columns where is is present
- **[X]** convert record into win ratio (e.g.: 15-3-0 --> 15/(15+3+0))
- **[X]** remove 'lbs.' from weight column, convert to kilograms
- **[ ]** convert features rounds, time, rounds_format into single feature indicating, how many % of total time fight lasted 
    - e.g.:
    - rounds = 2, time = 4:19, rounds_format = 3x5min, thus we know that fight lasted 1 whole round of 5 minutes + 4 min 19 sec of the second round, which adds up to 9 min 19 sec out of 3x5 = 15 mins total
    - converting minutes into seconds:
    - 9 * 60 = 540, 540 + 19 = 559 (that many seconds fight lasted), 15 * 60 = 900 (that many seconds it could have lasted max)
    - now we just divide 559 by 900 - 559/900 and get out new feature value
- **[ ]** change winner column values for:
    - 1, if Red corner fighter wins
    - 0, if Blue corner fighter wins
- **[ ]** OHE method column

In [2017]:
df = df.replace('%', '', regex=True)

# Win ratio

In [2018]:
df['Red_Record'].str.split(' ')

0                 [15-3-0]
1                [28-13-0]
2        [12-4-0, (1, NC)]
3                 [28-9-0]
4                 [15-9-0]
               ...
6501             [27-21-1]
6503             [19-12-1]
6504             [23-22-1]
6505    [91-22-5, (1, NC)]
6506             [17-16-0]
Name: Red_Record, Length: 6437, dtype: object

In [2019]:
print(set(df['Red_Record'].str.split(' ').apply(lambda x: len(x))))
assert set(df['Red_Record'].str.split(' ').str[0].str.split('-').apply(lambda x: len(x))) == {3}

{1, 3}

- Seems safe to asume that only patterns are:
    - 15-3-0
    - 12-4-0 (1, NC)

In [2020]:
def record_to_ratio(df, color):
    return df[color + 'Record'].str.split(' ').apply(lambda x: x).str[0].str.split('-').apply(
        lambda x: float(x[0])/(float(x[0]) + float(x[1]) + float(x[2])) * 100
    )

In [2021]:
colors = ['Red_', 'Blue_']
for color in colors:
    df[color + 'Winrate'] = record_to_ratio(df, color)

In [2022]:
df.head(5).transpose();

# Weight to kg

In [2023]:
def get_kg_weight(df, color):
    return df[color + 'Weight'].str.split(' ').str[0].apply(
        lambda x: round(float(x)/2.20462, 1)
    )

In [2024]:
# df['Red_Weight'].str.split(' ').str[0].apply(lambda x: round(float(x)/2.20462, 1))
colors = ['Red_', 'Blue_']
for color in colors:
    df[color + 'Weight'] = get_kg_weight(df, color)

In [2025]:
df.head(5).transpose();

# Time to seconds

In [2026]:
df.head(5).transpose()

,0,1,2,3,4
weight_division,Women's Flyweight Bout,Bantamweight Bout,Middleweight Bout,Bantamweight Bout,Light Heavyweight Bout
method,Decision - Unanimous,KO/TKO,KO/TKO,Decision - Unanimous,KO/TKO
rounds,5,2,2,3,1
time,5:00,4:19,3:12,5:00,1:28
rounds_format,5 Rnd (5-5-5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5),3 Rnd (5-5-5)
referee,Mark Smith,Herb Dean,Chris Tognoni,Kerry Hatley,Mark Smith
Red_Name,Alexa Grasso,Cub Swanson,Jordan Wright,Raphael Assuncao,Misha Cirkunov
Red_Record,15-3-0,28-13-0,12-4-0 (1 NC),28-9-0,15-9-0
Red_Height,165.1,172.72,187.96,165.1,190.5
Red_Weight,56.7,61.2,83.9,61.2,93.0
Red_STANCE,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox
Red_DOB,1993,1983,1991,1982,1987
Red_SLpM,5.14,4.68,5.67,3.24,3.86
Red_Str. Acc.,44,50,65,41,51
Red_SApM,4.02,3.73,7.54,2.41,3.06
Red_Str. Def,61,60,32,67,57
Red_TD Avg.,0.44,1.09,3.6,1.47,4.15
Red_TD Acc.,57,52,50,38,39
Red_TD Def.,64,61,100,78,76
Red_Sub. Avg.,0.6,0.4,0.7,0.3,1.7
Blue_Name,Viviane Araujo,Jonathan Martinez,Dusko Todorovic,Victor Henry,Alonzo Menifield
Blue_Record,11-4-0,17-4-0,12-3-0,22-6-0,13-3-0
Blue_Height,162.56,172.72,185.42,170.18,182.88
Blue_Weight,56.7,61.2,83.9,61.2,93.0
Blue_STANCE,Orthodox,Southpaw,Orthodox,Switch,Orthodox
Blue_DOB,1986,1994,1994,1987,1987
Blue_SLpM,4.82,4.84,5.64,7.87,3.91
Blue_Str. Acc.,48,49,57,49,56
Blue_SApM,5.33,3.88,4.54,6.47,3.24
Blue_Str. Def,56,58,47,47,52
Blue_TD Avg.,2.03,0.51,0.99,0.0,0.81
Blue_TD Acc.,48,45,12,0,30
Blue_TD Def.,90,70,45,75,85
Blue_Sub. Avg.,0.5,0.0,0.0,0.0,0.2
Winner,Alexa Grasso,Jonathan Martinez,Dusko Todorovic,Raphael Assuncao,Alonzo Menifield
Red_Winrate,83.333333,68.292683,75.0,75.675676,62.5
Blue_Winrate,73.333333,80.952381,80.0,78.571429,81.25

### Reformating time column, indicating minutes and seconds spent in the last round, to seconds only

In [2027]:
df['time'] = df['time'].apply(lambda x: x.split(':')).apply(lambda x: 60*int(x[0]) + int(x[1]))
df['time']

0       300
1       259
2       192
3       300
4        88
       ...
6501     81
6503    596
6504     43
6505    720
6506    180
Name: time, Length: 6437, dtype: int64

In [2028]:
df[['rounds', 'time', 'rounds_format']]

      rounds  time      rounds_format
0          5   300  5 Rnd (5-5-5-5-5)
1          2   259      3 Rnd (5-5-5)
2          2   192      3 Rnd (5-5-5)
3          3   300      3 Rnd (5-5-5)
4          1    88      3 Rnd (5-5-5)
...      ...   ...                ...
6501       1    81  1 Rnd + OT (12-3)
6503       1   596  1 Rnd + OT (12-3)
6504       1    43  1 Rnd + OT (12-3)
6505       1   720  1 Rnd + OT (12-3)
6506       2   180  1 Rnd + OT (12-3)

[6437 rows x 3 columns]

### Rounds format parsing

In [2029]:
df['rounds_format']

0       5 Rnd (5-5-5-5-5)
1           3 Rnd (5-5-5)
2           3 Rnd (5-5-5)
3           3 Rnd (5-5-5)
4           3 Rnd (5-5-5)
              ...
6501    1 Rnd + OT (12-3)
6503    1 Rnd + OT (12-3)
6504    1 Rnd + OT (12-3)
6505    1 Rnd + OT (12-3)
6506    1 Rnd + OT (12-3)
Name: rounds_format, Length: 6437, dtype: object

In [2030]:
def get_rounds_array(x):
    return x.split('(')[1].strip(')').split('-')

In [2031]:
df['rounds_format'] = df['rounds_format'].apply(lambda x: get_rounds_array(x))
df['rounds_format']

0       [5, 5, 5, 5, 5]
1             [5, 5, 5]
2             [5, 5, 5]
3             [5, 5, 5]
4             [5, 5, 5]
             ...
6501            [12, 3]
6503            [12, 3]
6504            [12, 3]
6505            [12, 3]
6506            [12, 3]
Name: rounds_format, Length: 6437, dtype: object

In [2032]:
df[['rounds', 'time', 'rounds_format']]

      rounds  time    rounds_format
0          5   300  [5, 5, 5, 5, 5]
1          2   259        [5, 5, 5]
2          2   192        [5, 5, 5]
3          3   300        [5, 5, 5]
4          1    88        [5, 5, 5]
...      ...   ...              ...
6501       1    81          [12, 3]
6503       1   596          [12, 3]
6504       1    43          [12, 3]
6505       1   720          [12, 3]
6506       2   180          [12, 3]

[6437 rows x 3 columns]

### Time length of the last round is already counted as 'time' feature. Hence we can get number of full-length rounds fought by substracting 1

In [2033]:
df['rounds'] = df['rounds'] - 1 
df['rounds']

0       4
1       1
2       1
3       2
4       0
       ..
6501    0
6503    0
6504    0
6505    0
6506    1
Name: rounds, Length: 6437, dtype: int64

In [2034]:
df[['rounds', 'time', 'rounds_format']]

      rounds  time    rounds_format
0          4   300  [5, 5, 5, 5, 5]
1          1   259        [5, 5, 5]
2          1   192        [5, 5, 5]
3          2   300        [5, 5, 5]
4          0    88        [5, 5, 5]
...      ...   ...              ...
6501       0    81          [12, 3]
6503       0   596          [12, 3]
6504       0    43          [12, 3]
6505       0   720          [12, 3]
6506       1   180          [12, 3]

[6437 rows x 3 columns]

In [2035]:
# function calculates number of seconds spent in full-length rounds
def full_rounds_time_spent(x):
    _sum = 0
    # n = number of full rounds
    n = int(x.split('[')[0])
    i = 0
    str_rounds = x.split('[')[1].strip(']')
    while n > 0:
        str_num = ''
        while str_rounds[i].isnumeric():
            str_num += str_rounds[i]
            i += 1
        if str_num != '':
            _sum += 60 * int(str_num)
            n -= 1
        i += 1
    return _sum

In [2036]:
full_rounds_time = df['rounds'].astype('str').str.cat(df['rounds_format'].astype('str')).apply(
    lambda x: full_rounds_time_spent(x)
)
full_rounds_time

0       1200
1        300
2        300
3        600
4          0
        ...
6501       0
6503       0
6504       0
6505       0
6506     720
Name: rounds, Length: 6437, dtype: int64

In [2037]:
# function calculates maximum fight length in seconds  
def max_time(x):
    x = list(x)
    _sum = 0
    for mins_per_round in x:
        _sum += 60 * int(mins_per_round)
    return _sum

In [2038]:
max_time_col = df['rounds_format'].apply(lambda x: max_time(x))
max_time_col

0       1500
1        900
2        900
3        900
4        900
        ...
6501     900
6503     900
6504     900
6505     900
6506     900
Name: rounds_format, Length: 6437, dtype: int64

In [2039]:
df['Fight_Length %'] = (df['time'] + full_rounds_time)/max_time_col * 100
df['Fight_Length %']

0       100.000000
1        62.111111
2        54.666667
3       100.000000
4         9.777778
           ...
6501      9.000000
6503     66.222222
6504      4.777778
6505     80.000000
6506    100.000000
Name: Fight_Length %, Length: 6437, dtype: float64

In [2040]:
df.head(5).drop(columns=['rounds', 'time', 'rounds_format', 'Red_Record', 'Blue_Record']).transpose()

,0,1,2,3,4
weight_division,Women's Flyweight Bout,Bantamweight Bout,Middleweight Bout,Bantamweight Bout,Light Heavyweight Bout
method,Decision - Unanimous,KO/TKO,KO/TKO,Decision - Unanimous,KO/TKO
referee,Mark Smith,Herb Dean,Chris Tognoni,Kerry Hatley,Mark Smith
Red_Name,Alexa Grasso,Cub Swanson,Jordan Wright,Raphael Assuncao,Misha Cirkunov
Red_Height,165.1,172.72,187.96,165.1,190.5
Red_Weight,56.7,61.2,83.9,61.2,93.0
Red_STANCE,Orthodox,Orthodox,Orthodox,Orthodox,Orthodox
Red_DOB,1993,1983,1991,1982,1987
Red_SLpM,5.14,4.68,5.67,3.24,3.86
Red_Str. Acc.,44,50,65,41,51
Red_SApM,4.02,3.73,7.54,2.41,3.06
Red_Str. Def,61,60,32,67,57
Red_TD Avg.,0.44,1.09,3.6,1.47,4.15
Red_TD Acc.,57,52,50,38,39
Red_TD Def.,64,61,100,78,76
Red_Sub. Avg.,0.6,0.4,0.7,0.3,1.7
Blue_Name,Viviane Araujo,Jonathan Martinez,Dusko Todorovic,Victor Henry,Alonzo Menifield
Blue_Height,162.56,172.72,185.42,170.18,182.88
Blue_Weight,56.7,61.2,83.9,61.2,93.0
Blue_STANCE,Orthodox,Southpaw,Orthodox,Switch,Orthodox
Blue_DOB,1986,1994,1994,1987,1987
Blue_SLpM,4.82,4.84,5.64,7.87,3.91
Blue_Str. Acc.,48,49,57,49,56
Blue_SApM,5.33,3.88,4.54,6.47,3.24
Blue_Str. Def,56,58,47,47,52
Blue_TD Avg.,2.03,0.51,0.99,0.0,0.81
Blue_TD Acc.,48,45,12,0,30
Blue_TD Def.,90,70,45,75,85
Blue_Sub. Avg.,0.5,0.0,0.0,0.0,0.2
Winner,Alexa Grasso,Jonathan Martinez,Dusko Todorovic,Raphael Assuncao,Alonzo Menifield
Red_Winrate,83.333333,68.292683,75.0,75.675676,62.5
Blue_Winrate,73.333333,80.952381,80.0,78.571429,81.25
Fight_Length %,100.0,62.111111,54.666667,100.0,9.777778

In [2042]:
df.to_csv('final data/data_2', index=False)